import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Верхний уровень вручную (3 продукта), внутри — автогенерация по папкам docs.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Введение',
      collapsed: false,
      link: {type: 'doc', id: 'introduction/index'},
      // Do not use autogenerated here: it would duplicate the linked index doc as a child item.
      items: ['introduction/network-basics', 'introduction/use-cases', 'introduction/limitations'],
    },
    {
      type: 'category',
      label: 'Meshtastic',
      collapsed: false,
      link: {type: 'doc', id: 'meshtastic/index'},
      items: [
        {
          type: 'category',
          label: 'Настройка ноды',
          link: {type: 'doc', id: 'node-setup/index'},
          items: [
            'node-setup/firmware',
            'node-setup/configuration',
            'node-setup/roles',
            'node-setup/testing',
            {
              type: 'category',
              label: 'Драйверы',
              link: {type: 'doc', id: 'node-setup/serial-drivers/index'},
              items: ['node-setup/serial-drivers/esp32', 'node-setup/serial-drivers/nrf52', 'node-setup/serial-drivers/test'],
            },
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          link: {type: 'doc', id: 'troubleshooting/index'},
          items: ['troubleshooting/not-visible'],
        },
        'community',
      ],
    },
    {
      type: 'category',
      label: 'Meshcore',
      collapsed: false,
      link: {type: 'doc', id: 'meshcore/index'},
      items: [],
    },
    {
      type: 'category',
      label: 'Reticulum',
      collapsed: false,
      link: {type: 'doc', id: 'reticulum/index'},
      items: [],
    },
    'catalog-devices',
    {
      type: 'category',
      label: 'Устройства',
      link: {type: 'doc', id: 'devices/index'},
      items: [
        {
          type: 'category',
          label: 'DIY',
          link: {type: 'doc', id: 'devices/diy/index'},
          items: ['devices/diy/boards'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Антенны',
      link: {type: 'doc', id: 'antennas/index'},
      items: ['antennas/ready-made', 'antennas/diy'],
    },
    'regulations',
  ],
};

export default sidebars;
